FROM golang:alpine AS builder
WORKDIR /app
ADD . .
RUN go mod download && \
    go build -o /tmp/item ./cmd/item/main.go

FROM alpine:latest AS final
COPY --from=builder /tmp/item /usr/local/bin/item
EXPOSE 8080
ENTRYPOINT /usr/local/bin/item
