FROM golang:alpine AS builder
WORKDIR /app
ADD . .
RUN go mod download && \
    go build -o /tmp/cartpresentation ./cmd/cartpresentation/main.go

FROM alpine:latest AS final
ENV SERVICE_NAME="cartpresentation"
COPY --from=builder /tmp/cartpresentation /usr/local/bin/cartpresentation
EXPOSE 8080
ENTRYPOINT /usr/local/bin/cartpresentation
