services:
  item:
    container_name: item
    hostname: item
    image: leonsteinhaeuser/demo-shop-item:dev
    build:
      context: .
      dockerfile: cmd/item/Containerfile
    ports:
      - "8081:8080"
    networks:
      - appnet
  cart:
    container_name: cart
    hostname: cart
    image: leonsteinhaeuser/demo-shop-cart:dev
    build:
      context: .
      dockerfile: cmd/cart/Containerfile
    ports:
      - "8082:8080"
    networks:
      - appnet
  cartpresentation:
    container_name: cartpresentation
    hostname: cartpresentation
    image: leonsteinhaeuser/demo-shop-cartpresentation:dev
    build:
      context: .
      dockerfile: cmd/cartpresentation/Containerfile
    environment:
      CART_SERVICE_URL: "http://cart:8080"
      ITEM_SERVICE_URL: "http://item:8080"
    ports:
      - "8083:8080"
    networks:
      - appnet
  user:
    container_name: user
    hostname: user
    image: leonsteinhaeuser/demo-shop-user:dev
    build:
      context: .
      dockerfile: cmd/user/Containerfile
    ports:
      - "8084:8080"
    networks:
      - appnet
  checkout:
    container_name: checkout
    hostname: checkout
    image: leonsteinhaeuser/demo-shop-checkout:dev
    build:
      context: .
      dockerfile: cmd/checkout/Containerfile
    environment:
      CART_SERVICE_URL: "http://cart:8080"
      ITEM_SERVICE_URL: "http://item:8080"
    ports:
      - "8085:8080"
    networks:
      - appnet
  frontend:
    container_name: frontend
    hostname: frontend
    image: leonsteinhaeuser/demo-shop-frontend:dev
    build:
      context: ./frontend
      dockerfile: Containerfile
    ports:
      - "8088:80"
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
      - ITEMS_SERVICE_URL=http://localhost:8081
      - USERS_SERVICE_URL=http://localhost:8084
      - CARTS_SERVICE_URL=http://localhost:8082
      - CHECKOUTS_SERVICE_URL=http://localhost:8085
      - CART_PRESENTATION_SERVICE_URL=http://localhost:8083
    depends_on:
      - item
      - cart
      - cartpresentation
      - user
      - checkout
    networks:
      - appnet

networks:
  appnet:
