services:
  item:
    container_name: item
    hostname: item
    image: leonsteinhaeuser/demo-shop-item:dev
    build:
      context: .
      dockerfile: cmd/item/Containerfile
    networks:
      - appnet
  cart:
    container_name: cart
    hostname: cart
    image: leonsteinhaeuser/demo-shop-cart:dev
    build:
      context: .
      dockerfile: cmd/cart/Containerfile
    networks:
      - appnet
  cartpresentation:
    container_name: cartpresentation
    hostname: cartpresentation
    image: leonsteinhaeuser/demo-shop-cartpresentation:dev
    build:
      context: .
      dockerfile: cmd/cartpresentation/Containerfile
    environment:
      CART_SERVICE_URL: "http://cart:8080"
      ITEM_SERVICE_URL: "http://item:8080"
    networks:
      - appnet
  user:
    container_name: user
    hostname: user
    image: leonsteinhaeuser/demo-shop-user:dev
    build:
      context: .
      dockerfile: cmd/user/Containerfile
    networks:
      - appnet
  checkout:
    container_name: checkout
    hostname: checkout
    image: leonsteinhaeuser/demo-shop-checkout:dev
    build:
      context: .
      dockerfile: cmd/checkout/Containerfile
    environment:
      CART_SERVICE_URL: "http://cart:8080"
      ITEM_SERVICE_URL: "http://item:8080"
    networks:
      - appnet
  gateway:
    container_name: gateway
    hostname: gateway
    image: leonsteinhaeuser/demo-shop-gateway:dev
    build:
      context: .
      dockerfile: cmd/gateway/Containerfile
    environment:
      USER_SERVICE_URL: "http://user:8080"
      CART_SERVICE_URL: "http://cart:8080"
      ITEM_SERVICE_URL: "http://item:8080"
      CHECKOUT_SERVICE_URL: "http://checkout:8080"
      CART_PRESENTATION_SERVICE_URL: "http://cartpresentation:8080"
      COOKIE_ENCRYPTION_KEY: "a_random_secret_key"
    ports:
      - "8080:8080"
    depends_on:
      - item
      - cart
      - cartpresentation
      - user
      - checkout
    networks:
      - appnet
  frontend:
    container_name: frontend
    hostname: frontend
    image: leonsteinhaeuser/demo-shop-frontend:dev
    build:
      context: .
      dockerfile: frontend/Containerfile
    ports:
      - "8088:80"
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
      - ITEMS_SERVICE_URL=http://localhost:8080
      - USERS_SERVICE_URL=http://localhost:8080
      - CARTS_SERVICE_URL=http://localhost:8080
      - CHECKOUTS_SERVICE_URL=http://localhost:8080
      - CART_PRESENTATION_SERVICE_URL=http://localhost:8080
    depends_on:
      - gateway

networks:
  appnet:
