services:
  item:
    container_name: item
    hostname: item
    image: leonsteinhaeuser/demo-shop-item:dev
    build:
      context: .
      dockerfile: cmd/item/Containerfile
    ports:
      - "8080:8080"
  cart:
    container_name: cart
    hostname: cart
    image: leonsteinhaeuser/demo-shop-cart:dev
    build:
      context: .
      dockerfile: cmd/cart/Containerfile
    ports:
      - "8081:8080"
  cartpresentation:
    container_name: cartpresentation
    hostname: cartpresentation
    image: leonsteinhaeuser/demo-shop-cartpresentation:dev
    build:
      context: .
      dockerfile: cmd/cartpresentation/Containerfile
    environment:
      CART_SERVICE_URL: "http://cart:8080"
      ITEM_SERVICE_URL: "http://item:8080"
    ports:
      - "8082:8080"
  user:
    container_name: user
    hostname: user
    image: leonsteinhaeuser/demo-shop-user:dev
    build:
      context: .
      dockerfile: cmd/user/Containerfile
    ports:
      - "8083:8080"
