apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  labels:
    app.kubernetes.io/name: demo-shop-gateway
    app.kubernetes.io/part-of: demo-shop
    app.kubernetes.io/component: gateway
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: demo

  source:
    repoURL: ghcr.io/leonsteinhaeuser/demo-shop
    chart: gateway
    targetRevision: "v0.4.1"
    helm:
      values: |
        replicaCount: 3

        image:
          repository: ghcr.io/leonsteinhaeuser/demo-shop-gateway
          tag: v0.4.0

        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi

        autoscaling:
          enabled: true
          minReplicas: 3
          maxReplicas: 30
          targetCPUUtilizationPercentage: 80

        upstreamServiceUrls:
          cartService: http://cart:8080
          itemService: http://item:8080
          userService: http://user:8080
          checkoutService: http://checkout:8080
          cartPresentationService: http://cart-presentation:8080

        secret:
          enabled: true
          value: a_random_secret_key

        # Prometheus PodMonitor configuration (not ServiceMonitor for gateway)
        podMonitor:
          enabled: true
          namespace: ""
          labels: {}
          interval: 30s
          scrapeTimeout: 10s
          path: /metrics
          relabelings: []
          metricRelabelings: []

        # Pod Disruption Budget configuration
        podDisruptionBudget:
          enabled: true
          minAvailable: 1
          labels: {}

        tracing:
          enabled: true
          endpoint: jaeger.jaeger:4317
          insecure: true
          protocol: grpc

  destination:
    server: https://kubernetes.default.svc
    namespace: demo-shop

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10
