apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: item
  labels:
    app.kubernetes.io/name: demo-shop-item
    app.kubernetes.io/part-of: demo-shop
    app.kubernetes.io/component: backend-service
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: demo
  source:
    repoURL: ghcr.io/leonsteinhaeuser/demo-shop
    chart: item
    targetRevision: "v0.4.7"
    helm:
      values: |
        replicaCount: 3

        image:
          repository: ghcr.io/leonsteinhaeuser/demo-shop-item
          tag: v0.4.7

        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi

        autoscaling:
          enabled: true
          minReplicas: 3
          maxReplicas: 50
          targetCPUUtilizationPercentage: 80

        # Prometheus PodMonitor configuration
        podMonitor:
          enabled: true
          namespace: ""
          labels: {}
          interval: 30s
          scrapeTimeout: 10s
          path: /metrics
          relabelings: []
          metricRelabelings: []

        # Pod Disruption Budget configuration
        podDisruptionBudget:
          enabled: true
          minAvailable: "30%"
          labels: {}

        tracing:
          enabled: true
          endpoint: jaeger.jaeger:4317
          insecure: true
          protocol: grpc

  destination:
    server: https://kubernetes.default.svc
    namespace: demo-shop

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10
